# Generated by Django 4.2.5 on 2023-10-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recon',
            name='trn_ref',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
